### ISSUE TITLE
Cannot call this method in a scroll callback

### ISSUE THREAD

**Issue by rupinderjeet** [NoNews/NoPaginate#6]
I received an exception while scrolling horizontally. I modified ErrorItem and LoadingItem for Horizontal and Vertical scrolls.

```
public interface LoadingItem extends BaseLinearLayoutManagerItem {

    LoadingItem VERTICAL = new LoadingItem() {

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

            View view = LayoutInflater.from(parent.getContext()).inflate(
                    R.layout.pagination_item_loading, parent, false
            );

            return new RecyclerView.ViewHolder(view) {};
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {}
    };

    LoadingItem HORIZONTAL = new LoadingItem() {

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

            View view = LayoutInflater.from(parent.getContext()).inflate(
                    R.layout.pagination_item_loading_horizontal_scroll, parent, false
            );

            return new RecyclerView.ViewHolder(view) {};
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {}
    };
}
```
And, then, I `setOrientation()` using PaginateBuilder:

```


    public PaginateBuilder setOrientation (PaginateOrientation orientation) {

        if (orientation == PaginateOrientation.HORIZONTAL) {
            setCustomErrorItem(ErrorItem.HORIZONTAL);
            setCustomLoadingItem(LoadingItem.HORIZONTAL);
        }
        else {
            setCustomErrorItem(ErrorItem.VERTICAL);
            setCustomLoadingItem(LoadingItem.VERTICAL);
        }

        return this;
    }
```

This is the exception I get:

```
03-24 10:06:48.274 W/RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
                                   java.lang.IllegalStateException:  android.support.v7.widget.RecyclerView{a136c97 VFED..... ......ID 0,0-450,273}, adapter:com.xxxxx.xxxx.utils.pagination.paginate.WrapperAdapter@9256e84, layout:android.support.v7.widget.LinearLayoutManager@ab4766d, context:com.xxxxx.xxxxx.view.modules.ecommerce.ShopActivity@5d48e36
                                       at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2673)
                                       at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5055)
                                       at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11540)
                                       at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6762)
                                       at com.xxxxx.xxxxx.utils.pagination.paginate.WrapperAdapterObserver.onChanged(WrapperAdapterObserver.java:50)
                                       at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11540)
                                       at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6762)
                                       at com.xxxxx.xxxxx.view.base.base_adapters.recycler_view_adapters.BaseListAdapter.informDataSetChanged(BaseListAdapter.java:902)
                                       at com.xxxxx.xxxxx.view.base.base_adapters.recycler_view_adapters.BaseListAdapter.setItems(BaseListAdapter.java:701)
                                       at com.xxxxxx.xxxxx.view.modules.ecommerce.features.product_similar.SimilarProductFragment.fetchSimilarProducts(SimilarProductFragment.java:97)
                                       at com.xxxxx.xxxx.view.modules.ecommerce.features.product_similar.SimilarProductFragment.onLoadMore(SimilarProductFragment.java:274)
                                       at com.xxxxx.xxxx.utils.pagination.paginate.Paginate.checkAdapterState(Paginate.java:76)
                                       at com.xxxxx.xxxxxx.utils.pagination.paginate.Paginate.checkScroll(Paginate.java:101)
                                       at com.xxxxx.xxxxx.utils.pagination.paginate.Paginate.access$000(Paginate.java:15)
                                       at com.xxxxx.xxxxx.utils.pagination.paginate.Paginate$1.onScrolled(Paginate.java:68)
                                       at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4722)
                                       at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1787)
                                       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2970)
                                       at android.view.View.dispatchTouchEvent(View.java:9303)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2242)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
                                   	at android.vi
```

Proposed solution is to wrap these calls in a `Handler.post()` maybe.

**Comment by NoNews** [comment]
Hi @rupinderjeet, I'm sorry for very late answer.

If I understand question right, you just can use horizontal linear layout manager in your adapter, just like this:

  ```
      final LinearLayoutManager layoutManager = new LinearLayoutManager(this,
       LinearLayoutManager.HORIZONTAL, false);
```
And, without library modification
